name: Scan CVEs

on: 
  pull_request:
  
jobs:
  scan:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout of tyk-identity-broker
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          
      - name: Change directory and Make
        run: |
          cd ci/CVEs
          make 