name: Scan CVEs

on: 
  workflow_dispatch:

jobs:
  scan:
    runs-on: ubuntu-latest
    
    steps:
      - name: checkout of tyk-identity-broker
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Change directory and Make
        run: |
          cd ci/CVEs
          make
   