name: Scan Docker Image CVE

on: 
  workflow_dispatch:
  push:
  pull_request:
    
jobs:
  scan:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - shell: bash
        run: |
          
          sudo apt update -y 
          sudo apt -y install build-essential
          sudo apt -y install make jq
          cd ci/imageScan
          make 
          mkdir scanreport
          cp unified.csv scanreport
          
      - uses: actions/upload-artifact@v3
        with: 
          name: scanreport
          path: ci/imageScan/scanreport/unified.csv

          


      
      




























