name: Scan Docker Image CVE

on: 
  workflow_dispatch:
  push:
  pull_request:
    
jobs:
  scan:
    runs-on: ubuntu-22.04

    steps:      
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
     - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@7b7aa264d83dc58691451798b4d117d53d21edfe
        with:
          
          image-ref: 'tykio/tyk-identity-broker:v1.2'
          format: 'json'
          output: 'trivy-results.json'
          severity: 'CRITICAL,HIGH'
          security-checks: 'vuln,secret,config'
          

      - name: Upload Trivy scan results as artifact
        uses: actions/upload-artifact@v3
        with:
          name: trivyreport
          path: ./trivy-results.json
        
        
        
      
          


      
          
                
      #     make
      #     mkdir scanreport
          
      #     cp unified.csv scanreport

      # - uses: actions/upload-artifact@v3
      #   with: 
      #     name: scanreport
      #     path: ci/imageScan/scanreport/unified.csv
     
        
          
          
            
         
     
          
          
      

          


      
      




























