name: Scan Docker Image CVE

on: 
  workflow_dispatch:
    inputs:
      imagetag:
        description: 'specify image tag'
        required: true
        type: string
      


    
jobs:
  scan:
    runs-on: ubuntu-22.04
    steps:      
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - shell: bash
        run: |
          apt-get update -y
          apt-get install -y build-essential wget gnupg lsb-release dpkg
          wget https://github.com/aquasecurity/trivy/releases/download/v0.32.0/trivy_0.32.0_Linux-64bit.deb
          dpkg -i trivy_0.32.0_Linux-64bit.deb

          trivy image --severity HIGH,CRITICAL tykio/tyk-identity-broker:v1.2 > tyk-identity-broker.json | tee >> unified.json
          trivy image --severity HIGH,CRITICAL tykio/tyk-mdcb-docker:v1.7 > tyk-mdcb-docker.json | tee >> unified.json
          trivy image --severity HIGH,CRITICAL tykio/tyk-hybrid-docker:v3.2 > tyk-hybrid-docker.json | tee >> unified.json
          trivy image --severity HIGH,CRITICAL tykio/tyk-plugin-compiler:v3.2 > tyk-plugin-compiler.json | tee >> unified.json
          trivy image --severity HIGH,CRITICAL tykio/tyk-dashboard:v3.2 > tyk-dashboard.json | tee >> unified.json
          trivy image --severity HIGH,CRITICAL tykio/tyk-gateway:v3.2 > tyk-gateway.json | tee >> unified.json
          trivy image --severity HIGH,CRITICAL tykio/tyk-pump-docker-pub:v1.6 > tyk-pump-docker-pub.json | tee >> unified.json

          pwd
          ls -al
      - name: Upload Trivy scan results as artifact
        uses: actions/upload-artifact@v3
        with:
          name: trivyreport
          path: ./unified.json





      

      
  # - name: Run Trivy vulnerability scanner
  #       uses: aquasecurity/trivy-action@7b7aa264d83dc58691451798b4d117d53d21edfe
  #       with:
          
  #         image-ref: 'tykio/tyk-identity-broker:${{inputs.imagetag}}'
  #         trivy-config: trivy.yaml
  #       - shell: bash
  #         Run |
  #     #       trivy image --severity HIGH,CRITICAL tykio/tyk-identity-broker:v1.2 > tyk-identity-broker.json | tee >> unified.json

      
      

      - name: Upload Trivy scan results as artifact
        uses: actions/upload-artifact@v3
        with:
          name: trivyreport
          path: ./trivy-results.csv
          
          
          
          
          
          
          
          
  # cat trivy-results.json | jq -r '.Results[] | (.Vulnerabilities, .Severity, .Library, .Title, .InstalledVersion, .FixedVersion)'

          
          
          
          
          
          



      
     
     

          

      



   
        
        
        
      
          


      
          
                
  #         make
  #         mkdir scanreport
          
  #         cp unified.csv scanreport

  #     - uses: actions/upload-artifact@v3
  #       with: 
  #         name: scanreport
  #         path: ci/imageScan/scanreport/unified.csv
     
        
          
          
            
         
     
          
          
      

          


      
      




























