name: Scan Docker Image CVE

on: 
  workflow_dispatch:
    inputs:
      imagetag:
        description: 'specify image tag'
        required: true
        type: string


    
jobs:
  scan:
    runs-on: ubuntu-22.04
    steps:      
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'tykio/tyk-identity-broker:${{inputs.imagetag}}'
          trivy-config: trivy.yaml
          

      - name: Upload Trivy scan results as artifact
        uses: actions/upload-artifact@v3
        with:
          name: trivyreport
          path: ./trivy-results.json



   
        
        
        
      
          


      
          
                
      #     make
      #     mkdir scanreport
          
      #     cp unified.csv scanreport

      # - uses: actions/upload-artifact@v3
      #   with: 
      #     name: scanreport
      #     path: ci/imageScan/scanreport/unified.csv
     
        
          
          
            
         
     
          
          
      

          


      
      




























