
name: Scan Docker Image CVE

on: 
  workflow_dispatch:
  
jobs:
  scan:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
          
      - name: Change directory and run Make
      - run: cd ci/imageScan
      - run: make
      

