
name: Scan Docker Image CVE

on: 
  workflow_dispatch:
  push:
  pull_request:
  
  
jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - run: |
          cd ci/imageScan
          make
      
      - name: 'update_worksheet'
        uses: jroehl/gsheet.action@v1.0.0 # you can specify '@release' to always have the latest changes
        with:
          spreadsheetId: <spreadsheetId>
          commands: | # list of commands, specified as a valid JSON string
            [
              { "command": "addWorksheet", "args": { "worksheetTitle": "<worksheetTitle>" }},
              { "command": "updateData", "args": { "data": [["A1", "A2", "A3"]] }},
              { "command": "getData", "args": { "range": "'<worksheetTitle>'!A2:B3" } }
            ]
        env:
          GSHEET_CLIENT_EMAIL: adequnl3@gmail.com
          GSHEET_PRIVATE_KEY: AIzaSyCPUYQFaOIe8poEECwmawcx6UMHJhG9oD8
      # - name: dump results
      #   env:
      #     #  the output of the action can be found in ${{ steps.update_worksheet.outputs.results }}
      #     RESULTS: ${{ steps.update_worksheet.outputs.results }}
      #   run: echo "$RESULTS" | jq

