name: Scan Docker Image CVE

on: 
  workflow_dispatch:
  push:
  pull_request:
    
jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - shell: bash
        run: |
          
          apt update -y 
          apt -y install build-essential
          apt -y install make jq curl
          mkdir -p ~/.docker/cli-plugins && \
          curl https://github.com/docker/scan-cli-plugin/releases/latest/download/docker-scan_linux_amd64 -L -s -S -o ~/.docker/cli-plugins/docker-scan &&\
          chmod +x ~/.docker/cli-plugins/docker-scan
          cd ci/imageScan
          docker scan --login --token dckr_pat_Ai3TrBdB1tBiios0gUu1qK_y-qE
          docker scan --accept-license --json --group-issues tykio/tyk-gateway:v3.2 | tee tyk-gateway.json
          docker scan --accept-license --json --group-issues tykio/tyk-dashboard:v3.2 |tee tyk-dashboard.json
          jq -r '.vulnerabilities | group_by(.packageName)[] | add | [ .packageName, .severity, .severityWithCritical, .version, .isUpgradeable, .isPatchable, .description, .from[0][0], .identifiers.CVE[] ] | @csv' tyk-gateway.json tyk-dashboard.json tyk-plugin-compiler.json tyk-hybrid-docker.json tyk-pump.json tyk-mdcb-docker.json tyk-identity-broker.json | tee unified.csv

          
      # - uses: actions/upload-artifact@v3
      #   with: 
      #     name: scanreport
      #     path: ci/imageScan/scanreport/unified.csv

          


      
      




























