
name: Scan Docker Image CVE

on: 
  workflow_dispatch:
  push:
  pull_request:
  
  
jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - run: |
          cd ci/imageScan
          make
          pwd
          ls

      
      - name: 'Send mail'
        uses: dawidd6/action-send-mail@v3

        with:
          server_address: smtp.gmail.com
          server_port: 465
          secure: true
          username: kaytest2022@gmail.com
          password: ipdizxhdrdfyozsf
          subject: Dockerfile Scan Result
          to: adequnl3@gmail.com
          from: kaytest2022@gmail.com
          body: Please check scan result
          attachments: /home/runner/work/tyk-identity-broker/tyk-identity-broker/ci/imageScan/tyk-identity-broker.json









