name: Scan Docker Image CVE

on: 
  workflow_dispatch:
  push:
  pull_request:
    
jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - name: Login to DockerHub
        if: startsWith(github.ref, 'refs/tags')
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - shell: bash
        run: |
          
          sudo apt update -y
          sudo apt -y install build-essential
          sudo apt-get  install gnupg lsb-release make jq curl

          curl -fsSL https://download.docker.com/linux/debian/gpg | sudo apt-key add - && \
          echo "deb [arch=amd64] https://download.docker.com/linux/debian $(lsb_release -cs) stable" > /etc/apt/sources.list.d/docker.list && \
          sudo apt-get update && apt-get install -y docker-ce-cli
          
          mkdir -p ~/.docker/cli-plugins && \
          curl https://github.com/docker/scan-cli-plugin/releases/latest/download/docker-scan_linux_amd64 -L -s -S -o ~/.docker/cli-plugins/docker-scan &&\
          sudo chmod +x ~/.docker/cli-plugins/docker-scan
          cd ci/imageScan
          docker scan --accept-license --json --group-issues tykio/tyk-gateway:v3.2 | tee tyk-gateway.json
          ls -al

     
      
          


      
          
                
      #     make
      #     mkdir scanreport
          
      #     cp unified.csv scanreport

      # - uses: actions/upload-artifact@v3
      #   with: 
      #     name: scanreport
      #     path: ci/imageScan/scanreport/unified.csv
     
        
          
          
            
         
     
          
          
      

          


      
      




























