name: Scan Docker Image CVE
on:
  push:
  workflow_dispatch:
    inputs:
      imagetag:
        description: 'specify image tag'
        required: true
        type: string
jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
        
      - name: Scan gateway
        uses: aquasecurity/trivy-action@7b7aa264d83dc58691451798b4d117d53d21edfe
        with:
          image-ref: 'tykio/tyk-gateway:${{inputs.imagetag}}'
          trivy-config: trivy.yaml

      - shell: bash
        id: report-generator
        run: |
          gateway_report=$(cat unified.json | jq -r '.Results[]? | .Target | .Vulnerabilities[]? |[.Description, .VulnerabilityID, .Severity, .PkgName, .InstalledVersion, .FixedVersion]' | jq -sc)
          echo "::set-output name=scanreport::$gateway_report"
          
      - name: 'update_worksheet'
        uses: jroehl/gsheet.action@v1.1.0 # you can specify '@release' to always have the latest changes
        continue-on-error: true
        with:
          spreadsheetId: 1iZOjBXgXPR9UQvSoNd7VtspS8TOQC9UTMkgWgBY2a3o
          commands: | # list of commands, specified as a valid JSON string
            [ 
              { "command": "removeWorksheet", "args": { "worksheetTitle": "tyk-gateway" }},
              { "command": "addWorksheet", "args": { "worksheetTitle": "tyk-gateway" }},
              { "command": "updateData", "args": { "data": ${{ steps.report-generator.outputs.scanreport }} }},
              { "command": "getData", "args": { "range": " 'tyk-gateway' !A2:B3" }}              
            ]
            
        env:
          GSHEET_CLIENT_EMAIL: ${{ secrets.GSHEET_CLIENT_EMAIL }}
          GSHEET_PRIVATE_KEY: ${{ secrets.GSHEET_PRIVATE_KEY }}
