name: Scan Docker Image CVE
on:
  push:
  workflow_dispatch:
    inputs:
      imagetag:
        description: 'specify image tag'
        required: true
        type: string
jobs:
  scan:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
        
      - name: Scan gateway
        uses: aquasecurity/trivy-action@7b7aa264d83dc58691451798b4d117d53d21edfe
        with:
          image-ref: 'tykio/tyk-gateway:${{inputs.imagetag}}'
          format: 'json'
          output: 'tyk-gateway.json'
          severity: 'CRITICAL,HIGH'
          security-checks: 'vuln,secret,config'
          timeout: '5m0s'

      - shell: bash
        id: report-generator
        run: |
          gatewayreport=$(cat tyk-gateway.json | jq -r '.Results[]? | .Vulnerabilities[]? | [.Description, .VulnerabilityID, .Severity, .PkgName, .InstalledVersion, .FixedVersion]' | jq -s)
          echo "::set-output name=scanreport::$gatewayreport"
          
      - name: 'update_worksheet'
        uses: jroehl/gsheet.action@v1.1.0 # you can specify '@release' to always have the latest changes
        with:
          spreadsheetId: 1iZOjBXgXPR9UQvSoNd7VtspS8TOQC9UTMkgWgBY2a3o
          commands: | # list of commands, specified as a valid JSON string
            [ 
              { "command": "addWorksheet", "args": { "worksheetTitle": "tyk-gateway" }},
              { "command": "updateData", "args": { "data": ${{ steps.report-generator.outputs.scanreport }} }},
              { "command": "getData", "args": { "range": " 'tyk-gateway' !A2:B3" }}              
            ]
            
        env:
          GSHEET_CLIENT_EMAIL: ${{ secrets.GSHEET_CLIENT_EMAIL }}
          GSHEET_PRIVATE_KEY: ${{ secrets.GSHEET_PRIVATE_KEY }}

          
      - name: Scan mdcb
        uses: aquasecurity/trivy-action@7b7aa264d83dc58691451798b4d117d53d21edfe
        with:
          image-ref: 'tykio/tyk-mdcb-docker:${{inputs.imagetag}}'
          format: 'json'
          output: 'tyk-mdcb-docker.json'
          severity: 'CRITICAL,HIGH'
          security-checks: 'vuln,secret,config'
          timeout: '5m0s'

      - shell: bash
        id: report-generator-2
        run: |
          mdcbreport=$(cat tyk-mdcb-docker.json | jq -r '.Results[]? | .Vulnerabilities[]? |[.Description, .VulnerabilityID, .Severity, .PkgName, .InstalledVersion, .FixedVersion]' | jq -sc)
          echo "::set-output name=scanreport::$mdcbreport"
          
      - name: 'update_worksheet'
        uses: jroehl/gsheet.action@v1.1.0 # you can specify '@release' to always have the latest changes
        with:
          spreadsheetId: 1iZOjBXgXPR9UQvSoNd7VtspS8TOQC9UTMkgWgBY2a3o
          commands: | # list of commands, specified as a valid JSON string
            [ 
              { "command": "addWorksheet", "args": { "worksheetTitle": "tyk-mdcb-docker" }},
              { "command": "updateData", "args": { "data": ${{ steps.report-generator-2.outputs.scanreport }} }},
              { "command": "getData", "args": { "range": " 'tyk-mdcb-docker' !A2:B3" }}              
            ]
            
        env:
          GSHEET_CLIENT_EMAIL: ${{ secrets.GSHEET_CLIENT_EMAIL }}
          GSHEET_PRIVATE_KEY: ${{ secrets.GSHEET_PRIVATE_KEY }}
