name: Scan Docker Image CVE

on:
  push:
  workflow_dispatch:
    inputs:
      imagetag:
        description: 'specify image tag'
        required: true
        type: string

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
    
      - name: Scan tyk-plugin-compiler
        uses: aquasecurity/trivy-action@7b7aa264d83dc58691451798b4d117d53d21edfe
        with:
          image-ref: 'tykio/tyk-plugin-compiler:v4.0'
          format: 'json'
          output: 'tyk-plugin-compiler.json'
          severity: 'CRITICAL,HIGH'
          security-checks: 'vuln,secret,config'
          timeout: '10m0s'
          
      - shell: bash
        id: report-generator3
        run: |
          scan_report=$(cat tyk-plugin-compiler.json | jq -r '.Results[]? | .Vulnerabilities[]? |[.Description, .VulnerabilityID, .Severity, .PkgName, .InstalledVersion, .FixedVersion]' | jq -sc)
          echo "::set-output name=scanreport::$scan_report"

      - name: 'update_worksheet'
        uses: jroehl/gsheet.action@v1.1.0 # you can specify '@release' to always have the latest changes
        with:
          spreadsheetId: 1tymoz9lVEW57Xhahfevf6IGm_v9nX5_JVJKxaXPQdlE
          commands: | # list of commands, specified as a valid JSON string
            [ 
              { "command": "addWorksheet", "args": { "worksheetTitle": "tyk-plugin-compiler" }},
              { "command": "updateData", "args": { "data": ${{ steps.report-generator3.outputs.scanreport }} }},
              { "command": "getData", "args": { "range": " 'tyk-plugin-compiler' !A2:B3" }}              
            ]
            
        env:
          GSHEET_CLIENT_EMAIL: ${{ secrets.GSHEET_CLIENT_EMAIL }}
          GSHEET_PRIVATE_KEY: ${{ secrets.GSHEET_PRIVATE_KEY }}

      - name: Scan hybrid docker
        uses: aquasecurity/trivy-action@7b7aa264d83dc58691451798b4d117d53d21edfe
        with:
          image-ref: 'tykio/tyk-hybrid-docker:${{inputs.imagetag}}'
          format: 'json'
          output: 'tyk-hybrid-docker.json'
          severity: 'CRITICAL,HIGH'
          security-checks: 'vuln,secret,config'
          timeout: '5m0s'
          
      - shell: bash
        id: report-generator2
        run: |
          scan_report=$(cat tyk-hybrid-docker.json | jq -r '.Results[]? | .Vulnerabilities[]? |[.Description, .VulnerabilityID, .Severity, .PkgName, .InstalledVersion, .FixedVersion]' | jq -sc)
          echo "::set-output name=scanreport::$scan_report"
          
      - name: 'update_worksheet'
        uses: jroehl/gsheet.action@v1.1.0 # you can specify '@release' to always have the latest changes
        with:
          spreadsheetId: 1tymoz9lVEW57Xhahfevf6IGm_v9nX5_JVJKxaXPQdlE
          commands: | # list of commands, specified as a valid JSON string
            [ 
              { "command": "addWorksheet", "args": { "worksheetTitle": "tyk-hybrid-docker" }},
              { "command": "updateData", "args": { "data": ${{ steps.report-generator2.outputs.scanreport }} }},
              { "command": "getData", "args": { "range": " 'tyk-hybrid-docker' !A2:B3" }}              
            ]
            
        env:
          GSHEET_CLIENT_EMAIL: ${{ secrets.GSHEET_CLIENT_EMAIL }}
          GSHEET_PRIVATE_KEY: ${{ secrets.GSHEET_PRIVATE_KEY }}
